apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: openstack-jaeger
spec:
  ingress:
    enabled: true
    annotations:
      vice-president: "true"
    hosts:
      - tracing.{{ .Values.global.region }}.cloud.sap
    tls:
      - hosts:
        - tracing.{{ .Values.global.region }}.cloud.sap
        secretName: tls-tracing-{{ .Values.global.region }}-cloud-sap

  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.hermes.svc:9200
