apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: openstack-jaeger
spec:
  ingress:
    enabled: true
    hosts:
    - tracing.{{ .Values.global.region }}.cloud.sap
  storage:
    type: elasticsearch
    options:
      es:
        service_urls: elasticsearch.hermes.svc:9200
