dependencies:
  - name: cc-rbac
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.3
  - name: manila-provisioner
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
  - name: node-problem-detector
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.3.3
