dependencies:
  - name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.8
  - name: memcached
    repository: file://../../common/memcached
    version: 0.0.3
  - condition: mysql_metrics.enabled
    name: mysql_metrics
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.5
  - name: utils
    repository: file://../../openstack/utils
    version: 0.1.1
